from models import Name


COMPUTER_SCIENTIST_NAMES = (
    Name(first='Simon', last='Peyton Jones'),
    Name(first='Hal', last='Abelson'),
    Name(first='Charles', last='Babbage'),
    Name(first='John', last='Backus'),
    Name(first='Tim', last='Berners-Lee'),
    Name(first='Sergey', last='Brin'),
    Name(first='Alonzo', last='Church'),
    Name(first='Haskell', last='Curry'),
    Name(first='Edsger', last='Dijkstra'),
    Name(first='Brendan', last='Eich'),
    Name(first='Douglas', last='Engelbart'),
    Name(first='Martin', last='Fowler'),
    Name(first='Grace', last='Hopper'),
    Name(first='Bill', last='Joy'),
    Name(first='Alan', last='Kay'),
    Name(first='Donald', last='Knuth'),
    Name(first='Rasmus', last='Lerdorf'),
    Name(first='Ada', last='Lovelace'),
    Name(first='John', last='McCarthy'),
    Name(first='Douglas', last='McIlroy'),
    Name(first='Marvin', last='Minsky'),
    Name(first='John', last='von Neumann'),
    Name(first='Larry', last='Page'),
    Name(first='Alan', last='Turing'),
    Name(first='Dennis', last='Ritchie'),
    Name(first='Guido', last='van Rossum'),
    Name(first='Bruce', last='Schneier'),
    Name(first='Adi', last='Shamir'),
    Name(first='Claude', last='Shannon'),
    Name(first='Richard', last='Stallman'),
    Name(first='Guy', last='Steele'),
    Name(first='Bjarne', last='Stroustrup'),
    Name(first='Gerald', last='Jay Sussman'),
    Name(first='Andrew', last='Tanenbaum'),
    Name(first='Ken', last='Thompson'),
    Name(first='Linus', last='Torvalds'),
    Name(first='Larry', last='Wall'),
)
